### ISSUE TITLE
Invalid Clearance Token?

### ISSUE THREAD

**Issue by 13obbyMack** [leinstay/gptbot#1]
Unfortunately, this is not working for me after cloning down the repo and building my bot; I'm seeing the following error exception in my console output attempting to run it directly in Node:

_PS C:\Temp\gptbot> node .\index.js
file:///C:/Temp/gptbot/node_modules/chatgpt/build/index.js:529
      throw new ChatGPTError("ChatGPT invalid clearance token");
            ^_

_ChatGPTError: ChatGPT invalid clearance token
    at new ChatGPTAPI (file:///C:/Temp/gptbot/node_modules/chatgpt/build/index.js:529:13)
    at file:///C:/Temp/gptbot/index.js:17:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)_

_Node.js v18.13.0_

I don't see a place to input my _clearanceToken_ in the _config.json_ referenced in the primary directory. Are you implying this value needs to be supplied here within the module JS -- _\gptbot\node_modules\chatgpt\build\index.js_?

**Comment by 13obbyMack** [comment]
Apologies... I see the initial release date of December 8th would likely predate the additional Cloudflare checks for this feature and thus the code would need to be updated to support it. I'm sure you're already aware, so I'll go ahead and close this issue out for now.
